/**
 * Onboarding hook words (Task 72, slice 4).
 *
 * The curated headword list is the SOURCE OF TRUTH for the onboarding demo:
 * `onboarding_demo_cards` only caches the rendered card per native language.
 *
 * Each learning language gets exactly three headwords chosen to demonstrate
 * what a plain dictionary cannot do:
 *
 * - `untranslatable` — a concept the interface language has no word for, so the
 *   card has to explain rather than translate.
 * - `idiom` — literal translation breaks; the card has to give the equivalent.
 * - `quirk` — a feature of the language itself (a particle, a construction, a
 *   sound pattern) that shows real command of it.
 * - `slang` — what people actually say in a chat or a bar and no textbook
 *   teaches; it is what makes a lapsed learner open the notification.
 *
 * Curation constraints (from the task spec): no vulgarity, no politics, no
 * culturally loaded jokes, and the point must survive translation into every
 * one of the 11 interface languages. Every generated card is still reviewed
 * once (`is_active`) before it is ever served.
 */

/** What a hook word is meant to demonstrate. */
export type HookWordCategory = "untranslatable" | "idiom" | "quirk" | "slang";

export interface HookWord {
  headword: string;
  category: HookWordCategory;
}

/**
 * Forty-odd curated headwords per supported learning language, keyed by ISO 639-1
 * code. Covers all 11 supported languages (en, ru, cs, de, fr, es, it, pt, uk,
 * pl, kk) — the same set the interface locales cover.
 *
 * The first three of each list are the original onboarding demo picks and MUST
 * keep their positions, and the first six stay put too: the onboarding keyboard
 * shows up to six (`MAX_DEMO_HOOKS`) and its `onb:hook:<lang>:<index>` callbacks
 * address a word by index, so moving them would repoint live buttons.
 *
 * Past those six, order is the send order: the preset layer serves the first
 * unseen word, and a lapsed user gets one every five days, so a word appended at
 * the end reaches nobody for months. New slang and idioms are therefore woven in
 * right after the pinned six (slang, idiom, older word, repeat). Moving a word
 * from index six on is safe — de-duplication matches the headword, not the index.
 *
 * The list is at least thirty long because it doubles as the re-engagement notification
 * fallback (see the preset layer in @polyglot/adapter-notifications): a user
 * with an empty dictionary should be able to receive one a day for a month
 * without ever seeing a repeat.
 */
export const HOOK_WORDS: Readonly<Record<string, readonly HookWord[]>> = {
  // English — an abstract noun most languages paraphrase, the canonical
  // "tea" idiom from the spec, and a phrasal verb whose parts mean nothing
  // on their own (the single biggest stumbling block for learners).
  en: [
    { headword: "serendipity", category: "untranslatable" },
    { headword: "it's not my cup of tea", category: "idiom" },
    { headword: "put up with", category: "quirk" },
    { headword: "sibling", category: "untranslatable" },
    { headword: "awkward", category: "untranslatable" },
    { headword: "cozy", category: "untranslatable" },
    { headword: "no cap", category: "slang" },
    { headword: "let the cat out of the bag", category: "idiom" },
    { headword: "overwhelmed", category: "untranslatable" },
    { headword: "lowkey", category: "slang" },
    { headword: "bite off more than you can chew", category: "idiom" },
    { headword: "small talk", category: "untranslatable" },
    { headword: "spill the tea", category: "slang" },
    { headword: "barking up the wrong tree", category: "idiom" },
    { headword: "pet peeve", category: "untranslatable" },
    { headword: "ghost", category: "slang" },
    { headword: "the elephant in the room", category: "idiom" },
    { headword: "wishful thinking", category: "untranslatable" },
    { headword: "salty", category: "slang" },
    { headword: "when pigs fly", category: "idiom" },
    { headword: "commute", category: "untranslatable" },
    { headword: "vibe check", category: "slang" },
    { headword: "it's raining cats and dogs", category: "idiom" },
    { headword: "break the ice", category: "idiom" },
    { headword: "FOMO", category: "slang" },
    { headword: "a hot potato", category: "idiom" },
    { headword: "hit the nail on the head", category: "idiom" },
    { headword: "rizz", category: "slang" },
    { headword: "the ball is in your court", category: "idiom" },
    { headword: "once in a blue moon", category: "idiom" },
    { headword: "touch grass", category: "slang" },
    { headword: "go down a rabbit hole", category: "idiom" },
    { headword: "the last straw", category: "idiom" },
    { headword: "live rent-free in someone's head", category: "slang" },
    { headword: "it's no use crying over spilled milk", category: "idiom" },
    { headword: "under the weather", category: "idiom" },
    { headword: "cost an arm and a leg", category: "idiom" },
    { headword: "spill the beans", category: "idiom" },
    { headword: "a piece of cake", category: "idiom" },
    { headword: "beat around the bush", category: "idiom" },
    { headword: "get cold feet", category: "idiom" },
    { headword: "call it a day", category: "idiom" },
    { headword: "on the same page", category: "idiom" },
    { headword: "get over", category: "quirk" },
    { headword: "look forward to", category: "quirk" },
    { headword: "run out of", category: "quirk" },
    { headword: "come up with", category: "quirk" },
    { headword: "put off", category: "quirk" },
    { headword: "take after", category: "quirk" },
    { headword: "used to", category: "quirk" },
  ],

  // Russian — the textbook untranslatable noun, a vivid idiom whose literal
  // reading ("to split wooden blocks") says nothing about idling, and the
  // all-purpose particle that means "let's", "come on" and "bye" at once.
  ru: [
    { headword: "тоска", category: "untranslatable" },
    { headword: "бить баклуши", category: "idiom" },
    { headword: "давай", category: "quirk" },
    { headword: "авось", category: "untranslatable" },
    { headword: "пошлость", category: "untranslatable" },
    { headword: "хамство", category: "untranslatable" },
    { headword: "кринж", category: "slang" },
    { headword: "вешать лапшу на уши", category: "idiom" },
    { headword: "уют", category: "untranslatable" },
    { headword: "залипать", category: "slang" },
    { headword: "когда рак на горе свистнет", category: "idiom" },
    { headword: "успеть", category: "untranslatable" },
    { headword: "краш", category: "slang" },
    { headword: "медвежья услуга", category: "idiom" },
    { headword: "разлука", category: "untranslatable" },
    { headword: "рофлить", category: "slang" },
    { headword: "ни рыба ни мясо", category: "idiom" },
    { headword: "заодно", category: "untranslatable" },
    { headword: "имба", category: "slang" },
    { headword: "сесть в калошу", category: "idiom" },
    { headword: "однолюб", category: "untranslatable" },
    { headword: "душнила", category: "slang" },
    { headword: "как с гуся вода", category: "idiom" },
    { headword: "водить за нос", category: "idiom" },
    { headword: "чилить", category: "slang" },
    { headword: "выеденного яйца не стоит", category: "idiom" },
    { headword: "как две капли воды", category: "idiom" },
    { headword: "хайп", category: "slang" },
    { headword: "собаку съесть", category: "idiom" },
    { headword: "спустя рукава", category: "idiom" },
    { headword: "изи", category: "slang" },
    { headword: "пускать пыль в глаза", category: "idiom" },
    { headword: "не в своей тарелке", category: "idiom" },
    { headword: "агриться", category: "slang" },
    { headword: "без царя в голове", category: "idiom" },
    { headword: "зарубить на носу", category: "idiom" },
    { headword: "делать из мухи слона", category: "idiom" },
    { headword: "остаться с носом", category: "idiom" },
    { headword: "душа в душу", category: "idiom" },
    { headword: "рукой подать", category: "idiom" },
    { headword: "как снег на голову", category: "idiom" },
    { headword: "бросать слова на ветер", category: "idiom" },
    { headword: "считать ворон", category: "idiom" },
    { headword: "ну", category: "quirk" },
    { headword: "же", category: "quirk" },
    { headword: "ничего", category: "quirk" },
    { headword: "ага", category: "quirk" },
    { headword: "мол", category: "quirk" },
    { headword: "разве", category: "quirk" },
    { headword: "вроде", category: "quirk" },
  ],

  // Czech — the spec's own examples: a verb for a whole social protocol
  // (ring once and hang up so the other person calls back), the vowel-less
  // tongue twister that shows Czech syllabic consonants, plus an idiom whose
  // literal reading ("to walk around hot porridge") hides "beat about the bush".
  cs: [
    { headword: "prozvonit", category: "untranslatable" },
    { headword: "chodit kolem horké kaše", category: "idiom" },
    { headword: "strč prst skrz krk", category: "quirk" },
    { headword: "litost", category: "untranslatable" },
    { headword: "pohoda", category: "untranslatable" },
    { headword: "šikovný", category: "untranslatable" },
    { headword: "hustý", category: "slang" },
    { headword: "nosit dříví do lesa", category: "idiom" },
    { headword: "stihnout", category: "untranslatable" },
    { headword: "kámoš", category: "slang" },
    { headword: "mít za ušima", category: "idiom" },
    { headword: "předevčírem", category: "untranslatable" },
    { headword: "makat", category: "slang" },
    { headword: "je to nad slunce jasnější", category: "idiom" },
    { headword: "pohodář", category: "untranslatable" },
    { headword: "prachy", category: "slang" },
    { headword: "koupit zajíce v pytli", category: "idiom" },
    { headword: "ponorka", category: "untranslatable" },
    { headword: "trapas", category: "slang" },
    { headword: "tahat za kratší konec", category: "idiom" },
    { headword: "blbnout", category: "untranslatable" },
    { headword: "pařit", category: "slang" },
    { headword: "vzít nohy na ramena", category: "idiom" },
    { headword: "mít se jako prase v žitě", category: "idiom" },
    { headword: "šprt", category: "slang" },
    { headword: "chytat lelky", category: "idiom" },
    { headword: "být v sedmém nebi", category: "idiom" },
    { headword: "kecat", category: "slang" },
    { headword: "je to pro mě španělská vesnice", category: "idiom" },
    { headword: "dělat z komára velblouda", category: "idiom" },
    { headword: "frajer", category: "slang" },
    { headword: "dělat mrtvého brouka", category: "idiom" },
    { headword: "mít máslo na hlavě", category: "idiom" },
    { headword: "mega", category: "slang" },
    { headword: "mít knedlík v krku", category: "idiom" },
    { headword: "padají trakaře", category: "idiom" },
    { headword: "mluvit do zdi", category: "idiom" },
    { headword: "mít kliku", category: "idiom" },
    { headword: "být v balíku", category: "idiom" },
    { headword: "držet palce", category: "idiom" },
    { headword: "je to za pět minut dvanáct", category: "idiom" },
    { headword: "ani ryba ani rak", category: "idiom" },
    { headword: "hodit flintu do žita", category: "idiom" },
    { headword: "no", category: "quirk" },
    { headword: "jo", category: "quirk" },
    { headword: "prostě", category: "quirk" },
    { headword: "vlastně", category: "quirk" },
    { headword: "aspoň", category: "quirk" },
    { headword: "spíš", category: "quirk" },
    { headword: "copak", category: "quirk" },
  ],

  // German — the spec's three: a compound noun for "a face badly in need of a
  // slap", the verb for making something worse by trying to improve it, and
  // the modal particle that contradicts a negative and has no English word.
  de: [
    { headword: "Backpfeifengesicht", category: "untranslatable" },
    { headword: "verschlimmbessern", category: "untranslatable" },
    { headword: "doch", category: "quirk" },
    { headword: "Fernweh", category: "untranslatable" },
    { headword: "Schadenfreude", category: "untranslatable" },
    { headword: "Torschlusspanik", category: "untranslatable" },
    { headword: "krass", category: "slang" },
    { headword: "Schwein haben", category: "idiom" },
    { headword: "Kummerspeck", category: "untranslatable" },
    { headword: "Digga", category: "slang" },
    { headword: "die Katze im Sack kaufen", category: "idiom" },
    { headword: "Fingerspitzengefühl", category: "untranslatable" },
    { headword: "chillen", category: "slang" },
    { headword: "jemandem einen Bären aufbinden", category: "idiom" },
    { headword: "Weltschmerz", category: "untranslatable" },
    { headword: "Bock haben", category: "slang" },
    { headword: "da steppt der Bär", category: "idiom" },
    { headword: "Feierabend", category: "untranslatable" },
    { headword: "lost", category: "slang" },
    { headword: "sich zum Affen machen", category: "idiom" },
    { headword: "Geborgenheit", category: "untranslatable" },
    { headword: "Alter", category: "slang" },
    { headword: "ich glaub, mein Schwein pfeift", category: "idiom" },
    { headword: "Gemütlichkeit", category: "untranslatable" },
    { headword: "cringe", category: "slang" },
    { headword: "auf dem Holzweg sein", category: "idiom" },
    { headword: "Ohrwurm", category: "untranslatable" },
    { headword: "Ehrenmann", category: "slang" },
    { headword: "das ist nicht mein Bier", category: "idiom" },
    { headword: "Vorfreude", category: "untranslatable" },
    { headword: "gönn dir", category: "slang" },
    { headword: "Hals- und Beinbruch", category: "idiom" },
    { headword: "Treppenwitz", category: "untranslatable" },
    { headword: "Kohle", category: "slang" },
    { headword: "die Kirche im Dorf lassen", category: "idiom" },
    { headword: "die Daumen drücken", category: "idiom" },
    { headword: "ins Fettnäpfchen treten", category: "idiom" },
    { headword: "Tomaten auf den Augen haben", category: "idiom" },
    { headword: "das ist mir Wurst", category: "idiom" },
    { headword: "die Nase voll haben", category: "idiom" },
    { headword: "unter vier Augen", category: "idiom" },
    { headword: "nur Bahnhof verstehen", category: "idiom" },
    { headword: "aus dem Häuschen sein", category: "idiom" },
    { headword: "mal", category: "quirk" },
    { headword: "eben", category: "quirk" },
    { headword: "halt", category: "quirk" },
    { headword: "schon", category: "quirk" },
    { headword: "wohl", category: "quirk" },
    { headword: "denn", category: "quirk" },
    { headword: "ja", category: "quirk" },
  ],

  // French — the feeling of being out of your own element, the spec's
  // "to have the cockroach" idiom, and `si`, the second "yes" reserved for
  // contradicting a negative question (the French counterpart of `doch`).
  fr: [
    { headword: "dépaysement", category: "untranslatable" },
    { headword: "avoir le cafard", category: "idiom" },
    { headword: "si", category: "quirk" },
    { headword: "flâner", category: "untranslatable" },
    { headword: "râler", category: "untranslatable" },
    { headword: "l'esprit de l'escalier", category: "untranslatable" },
    { headword: "stylé", category: "slang" },
    { headword: "avoir la pêche", category: "idiom" },
    { headword: "retrouvailles", category: "untranslatable" },
    { headword: "grave", category: "slang" },
    { headword: "coûter les yeux de la tête", category: "idiom" },
    { headword: "terroir", category: "untranslatable" },
    { headword: "ouf", category: "slang" },
    { headword: "quand les poules auront des dents", category: "idiom" },
    { headword: "empêchement", category: "untranslatable" },
    { headword: "relou", category: "slang" },
    { headword: "raconter des salades", category: "idiom" },
    { headword: "avant-hier", category: "untranslatable" },
    { headword: "avoir le seum", category: "slang" },
    { headword: "c'est la fin des haricots", category: "idiom" },
    { headword: "bof", category: "untranslatable" },
    { headword: "chelou", category: "slang" },
    { headword: "appeler un chat un chat", category: "idiom" },
    { headword: "poser un lapin", category: "idiom" },
    { headword: "bouffer", category: "slang" },
    { headword: "avoir un poil dans la main", category: "idiom" },
    { headword: "coup de foudre", category: "idiom" },
    { headword: "fringues", category: "slang" },
    { headword: "tomber des nues", category: "idiom" },
    { headword: "avoir un chat dans la gorge", category: "idiom" },
    { headword: "frangin", category: "slang" },
    { headword: "se prendre un râteau", category: "idiom" },
    { headword: "tomber dans les pommes", category: "idiom" },
    { headword: "bosser", category: "slang" },
    { headword: "avoir d'autres chats à fouetter", category: "idiom" },
    { headword: "revenons à nos moutons", category: "idiom" },
    { headword: "il pleut des cordes", category: "idiom" },
    { headword: "mettre son grain de sel", category: "idiom" },
    { headword: "avoir le coup de main", category: "idiom" },
    { headword: "donner sa langue au chat", category: "idiom" },
    { headword: "être à côté de la plaque", category: "idiom" },
    { headword: "poser une colle", category: "idiom" },
    { headword: "avoir le cœur sur la main", category: "idiom" },
    { headword: "quand même", category: "quirk" },
    { headword: "du coup", category: "quirk" },
    { headword: "enfin", category: "quirk" },
    { headword: "hein", category: "quirk" },
    { headword: "on", category: "quirk" },
    { headword: "y", category: "quirk" },
    { headword: "en", category: "quirk" },
  ],

  // Spanish — the spec's `sobremesa` (the conversation that outlives the meal),
  // an idiom that literally reads "to be eaten bread", and a verb that packs
  // "to use or wear something for the very first time" into one word.
  es: [
    { headword: "sobremesa", category: "untranslatable" },
    { headword: "ser pan comido", category: "idiom" },
    { headword: "estrenar", category: "quirk" },
    { headword: "friolero", category: "untranslatable" },
    { headword: "anteayer", category: "untranslatable" },
    { headword: "tocayo", category: "untranslatable" },
    { headword: "guay", category: "slang" },
    { headword: "dar gato por liebre", category: "idiom" },
    { headword: "madrugar", category: "untranslatable" },
    { headword: "mola", category: "slang" },
    { headword: "estar hasta las narices", category: "idiom" },
    { headword: "empalagar", category: "untranslatable" },
    { headword: "flipar", category: "slang" },
    { headword: "dar calabazas", category: "idiom" },
    { headword: "desvelarse", category: "untranslatable" },
    { headword: "tío", category: "slang" },
    { headword: "no hay tu tía", category: "idiom" },
    { headword: "puente", category: "untranslatable" },
    { headword: "chaval", category: "slang" },
    { headword: "tirar la casa por la ventana", category: "idiom" },
    { headword: "merienda", category: "untranslatable" },
    { headword: "curro", category: "slang" },
    { headword: "estar como pez en el agua", category: "idiom" },
    { headword: "vergüenza ajena", category: "untranslatable" },
    { headword: "pasta", category: "slang" },
    { headword: "buscarle tres pies al gato", category: "idiom" },
    { headword: "trasnochar", category: "untranslatable" },
    { headword: "chévere", category: "slang" },
    { headword: "a otro perro con ese hueso", category: "idiom" },
    { headword: "estar en las nubes", category: "idiom" },
    { headword: "¿qué onda?", category: "slang" },
    { headword: "irse por las ramas", category: "idiom" },
    { headword: "tomar el pelo", category: "idiom" },
    { headword: "postureo", category: "slang" },
    { headword: "estar en el ajo", category: "idiom" },
    { headword: "no tener pelos en la lengua", category: "idiom" },
    { headword: "echar una mano", category: "idiom" },
    { headword: "meter la pata", category: "idiom" },
    { headword: "ponerse las pilas", category: "idiom" },
    { headword: "costar un ojo de la cara", category: "idiom" },
    { headword: "dar en el clavo", category: "idiom" },
    { headword: "estar como una cabra", category: "idiom" },
    { headword: "ir al grano", category: "idiom" },
    { headword: "ojalá", category: "quirk" },
    { headword: "pues", category: "quirk" },
    { headword: "vale", category: "quirk" },
    { headword: "ya", category: "quirk" },
    { headword: "venga", category: "quirk" },
    { headword: "hombre", category: "quirk" },
    { headword: "que", category: "quirk" },
  ],

  // Italian — the post-lunch drowsiness that has no one-word equivalent, the
  // good-luck wish that literally sends you "into the wolf's mouth", and the
  // particle that swings between "maybe", "if only" and "I wish".
  it: [
    { headword: "abbiocco", category: "untranslatable" },
    { headword: "in bocca al lupo", category: "idiom" },
    { headword: "magari", category: "quirk" },
    { headword: "meriggiare", category: "untranslatable" },
    { headword: "gattara", category: "untranslatable" },
    { headword: "menefreghista", category: "untranslatable" },
    { headword: "figo", category: "slang" },
    { headword: "avere un diavolo per capello", category: "idiom" },
    { headword: "culaccino", category: "untranslatable" },
    { headword: "boh", category: "slang" },
    { headword: "costare un occhio della testa", category: "idiom" },
    { headword: "apericena", category: "untranslatable" },
    { headword: "che ansia", category: "slang" },
    { headword: "essere come il prezzemolo", category: "idiom" },
    { headword: "struggimento", category: "untranslatable" },
    { headword: "gasato", category: "slang" },
    { headword: "fare un buco nell'acqua", category: "idiom" },
    { headword: "pantofolaio", category: "untranslatable" },
    { headword: "spaccare", category: "slang" },
    { headword: "piove a catinelle", category: "idiom" },
    { headword: "l'altroieri", category: "untranslatable" },
    { headword: "stare in fissa", category: "slang" },
    { headword: "sputare il rospo", category: "idiom" },
    { headword: "non vedo l'ora", category: "idiom" },
    { headword: "raga", category: "slang" },
    { headword: "essere una buona forchetta", category: "idiom" },
    { headword: "essere al verde", category: "idiom" },
    { headword: "sclerare", category: "slang" },
    { headword: "non avere peli sulla lingua", category: "idiom" },
    { headword: "prendere due piccioni con una fava", category: "idiom" },
    { headword: "svoltare", category: "slang" },
    { headword: "cercare il pelo nell'uovo", category: "idiom" },
    { headword: "avere le mani in pasta", category: "idiom" },
    { headword: "bella", category: "slang" },
    { headword: "acqua passata", category: "idiom" },
    { headword: "acqua in bocca", category: "idiom" },
    { headword: "che pizza", category: "idiom" },
    { headword: "fare il portoghese", category: "idiom" },
    { headword: "cadere dalle nuvole", category: "idiom" },
    { headword: "avere la testa fra le nuvole", category: "idiom" },
    { headword: "fare orecchie da mercante", category: "idiom" },
    { headword: "essere in gamba", category: "idiom" },
    { headword: "tirare il pacco", category: "idiom" },
    { headword: "ci", category: "quirk" },
    { headword: "ne", category: "quirk" },
    { headword: "mica", category: "quirk" },
    { headword: "allora", category: "quirk" },
    { headword: "dai", category: "quirk" },
    { headword: "beh", category: "quirk" },
    { headword: "proprio", category: "quirk" },
  ],

  // Portuguese — the canonical untranslatable noun, an idiom that literally
  // reads "to swallow frogs", and a diminutive that names a whole social
  // ritual rather than a small coffee.
  pt: [
    { headword: "saudade", category: "untranslatable" },
    { headword: "engolir sapos", category: "idiom" },
    { headword: "cafezinho", category: "quirk" },
    { headword: "cafuné", category: "untranslatable" },
    { headword: "desenrascanço", category: "untranslatable" },
    { headword: "xodó", category: "untranslatable" },
    { headword: "mano", category: "slang" },
    { headword: "pisar na bola", category: "idiom" },
    { headword: "friorento", category: "untranslatable" },
    { headword: "cara", category: "slang" },
    { headword: "ficar a ver navios", category: "idiom" },
    { headword: "anteontem", category: "untranslatable" },
    { headword: "valeu", category: "slang" },
    { headword: "quem não tem cão caça com gato", category: "idiom" },
    { headword: "madrugar", category: "untranslatable" },
    { headword: "da hora", category: "slang" },
    { headword: "enfiar o pé na jaca", category: "idiom" },
    { headword: "calorento", category: "untranslatable" },
    { headword: "rolê", category: "slang" },
    { headword: "custar os olhos da cara", category: "idiom" },
    { headword: "malandro", category: "untranslatable" },
    { headword: "zoar", category: "slang" },
    { headword: "chorar pitangas", category: "idiom" },
    { headword: "pagar o pato", category: "idiom" },
    { headword: "treta", category: "slang" },
    { headword: "segurar vela", category: "idiom" },
    { headword: "chutar o balde", category: "idiom" },
    { headword: "top", category: "slang" },
    { headword: "estar com a faca e o queijo na mão", category: "idiom" },
    { headword: "ficar de molho", category: "idiom" },
    { headword: "fixe", category: "slang" },
    { headword: "arregaçar as mangas", category: "idiom" },
    { headword: "dar com os burros n'água", category: "idiom" },
    { headword: "bué", category: "slang" },
    { headword: "ter macaquinhos no sótão", category: "idiom" },
    { headword: "encher linguiça", category: "idiom" },
    { headword: "tirar o cavalinho da chuva", category: "idiom" },
    { headword: "matar dois coelhos com uma cajadada", category: "idiom" },
    { headword: "fazer vista grossa", category: "idiom" },
    { headword: "estar com a pulga atrás da orelha", category: "idiom" },
    { headword: "dar um jeitinho", category: "idiom" },
    { headword: "nem que a vaca tussa", category: "idiom" },
    { headword: "viajar na maionese", category: "idiom" },
    { headword: "pois é", category: "quirk" },
    { headword: "né", category: "quirk" },
    { headword: "então", category: "quirk" },
    { headword: "cadê", category: "quirk" },
    { headword: "mesmo", category: "quirk" },
    { headword: "ficar", category: "quirk" },
    { headword: "tomara", category: "quirk" },
  ],

  // Ukrainian — the warm land birds fly to for the winter (one noun, no
  // equivalent), an idiom measuring quantity by "as much as a cat cried",
  // and an old adverb of admiration that no interface language renders in
  // one word.
  uk: [
    { headword: "вирій", category: "untranslatable" },
    { headword: "як кіт наплакав", category: "idiom" },
    { headword: "нівроку", category: "quirk" },
    { headword: "затишок", category: "untranslatable" },
    { headword: "щирість", category: "untranslatable" },
    { headword: "домівка", category: "untranslatable" },
    { headword: "топчик", category: "slang" },
    { headword: "замилювати очі", category: "idiom" },
    { headword: "розрада", category: "untranslatable" },
    { headword: "лайкати", category: "slang" },
    { headword: "коли рак на горі свисне", category: "idiom" },
    { headword: "позавчора", category: "untranslatable" },
    { headword: "чілити", category: "slang" },
    { headword: "ні пава ні ґава", category: "idiom" },
    { headword: "досвітки", category: "untranslatable" },
    { headword: "хейтити", category: "slang" },
    { headword: "накивати п'ятами", category: "idiom" },
    { headword: "обійми", category: "untranslatable" },
    { headword: "зависати", category: "slang" },
    { headword: "собаку з'їсти", category: "idiom" },
    { headword: "наснага", category: "untranslatable" },
    { headword: "бро", category: "slang" },
    { headword: "з голочки", category: "idiom" },
    { headword: "лізти поперед батька в пекло", category: "idiom" },
    { headword: "го", category: "slang" },
    { headword: "товкти воду в ступі", category: "idiom" },
    { headword: "дати гарбуза", category: "idiom" },
    { headword: "кринж", category: "slang" },
    { headword: "як горох об стіну", category: "idiom" },
    { headword: "бити байдики", category: "idiom" },
    { headword: "краш", category: "slang" },
    { headword: "ловити гав", category: "idiom" },
    { headword: "тримати кулаки", category: "idiom" },
    { headword: "вайб", category: "slang" },
    { headword: "не мати клепки в голові", category: "idiom" },
    { headword: "робити з мухи слона", category: "idiom" },
    { headword: "як сніг на голову", category: "idiom" },
    { headword: "ні пуху ні пера", category: "idiom" },
    { headword: "водити за носа", category: "idiom" },
    { headword: "рукою подати", category: "idiom" },
    { headword: "пекти раків", category: "idiom" },
    { headword: "брати близько до серця", category: "idiom" },
    { headword: "теревені правити", category: "idiom" },
    { headword: "ну", category: "quirk" },
    { headword: "ж", category: "quirk" },
    { headword: "хіба", category: "quirk" },
    { headword: "аж", category: "quirk" },
    { headword: "мабуть", category: "quirk" },
    { headword: "нехай", category: "quirk" },
    { headword: "ото", category: "quirk" },
  ],

  // Polish — the verb for improvising a way around a problem, an idiom that
  // literally reads "a roll with butter", and `no`, which is a relaxed "yeah"
  // and the most useful false friend in the language.
  pl: [
    { headword: "kombinować", category: "untranslatable" },
    { headword: "bułka z masłem", category: "idiom" },
    { headword: "no", category: "quirk" },
    { headword: "załatwić", category: "untranslatable" },
    { headword: "dobranocka", category: "untranslatable" },
    { headword: "smacznego", category: "untranslatable" },
    { headword: "spoko", category: "slang" },
    { headword: "to nie moja bajka", category: "idiom" },
    { headword: "przedwczoraj", category: "untranslatable" },
    { headword: "ogarnąć", category: "slang" },
    { headword: "nie mój cyrk, nie moje małpy", category: "idiom" },
    { headword: "doba", category: "untranslatable" },
    { headword: "masakra", category: "slang" },
    { headword: "wpuścić kogoś w maliny", category: "idiom" },
    { headword: "tęsknota", category: "untranslatable" },
    { headword: "czaić", category: "slang" },
    { headword: "obiecywać gruszki na wierzbie", category: "idiom" },
    { headword: "kwadrans", category: "untranslatable" },
    { headword: "siema", category: "slang" },
    { headword: "kupić kota w worku", category: "idiom" },
    { headword: "pogodny", category: "untranslatable" },
    { headword: "sztos", category: "slang" },
    { headword: "wyjść jak Zabłocki na mydle", category: "idiom" },
    { headword: "rzucać grochem o ścianę", category: "idiom" },
    { headword: "kasa", category: "slang" },
    { headword: "leje jak z cebra", category: "idiom" },
    { headword: "być nie w sosie", category: "idiom" },
    { headword: "luz", category: "slang" },
    { headword: "mieć nosa", category: "idiom" },
    { headword: "mieć muchy w nosie", category: "idiom" },
    { headword: "beka", category: "slang" },
    { headword: "z motyką na słońce", category: "idiom" },
    { headword: "trzymać kciuki", category: "idiom" },
    { headword: "essa", category: "slang" },
    { headword: "wziąć nogi za pas", category: "idiom" },
    { headword: "wiercić dziurę w brzuchu", category: "idiom" },
    { headword: "raz na ruski rok", category: "idiom" },
    { headword: "co ma piernik do wiatraka", category: "idiom" },
    { headword: "robić z igły widły", category: "idiom" },
    { headword: "czuć się jak ryba w wodzie", category: "idiom" },
    { headword: "spaść z księżyca", category: "idiom" },
    { headword: "mieć węża w kieszeni", category: "idiom" },
    { headword: "poszło jak z płatka", category: "idiom" },
    { headword: "przecież", category: "quirk" },
    { headword: "właśnie", category: "quirk" },
    { headword: "chyba", category: "quirk" },
    { headword: "aż", category: "quirk" },
    { headword: "trochę", category: "quirk" },
    { headword: "też", category: "quirk" },
    { headword: "no dobra", category: "quirk" },
  ],

  // Kazakh — the spread table that stands for hospitality itself, an idiom of
  // joy that literally reads "his crown reached the sky", and the standard
  // polite greeting that literally asks "are you healthy?" and carries the
  // question particle every learner meets first.
  kk: [
    { headword: "дастархан", category: "untranslatable" },
    { headword: "төбесі көкке жетті", category: "idiom" },
    { headword: "сәлеметсіз бе", category: "quirk" },
    { headword: "қонақжайлылық", category: "untranslatable" },
    { headword: "бата", category: "untranslatable" },
    { headword: "шаңырақ", category: "untranslatable" },
    { headword: "ойбай", category: "quirk" },
    { headword: "ит пен мысықтай", category: "idiom" },
    { headword: "сыбаға", category: "untranslatable" },
    { headword: "бәрекелді", category: "quirk" },
    { headword: "қас пен көздің арасында", category: "idiom" },
    { headword: "ерулік", category: "untranslatable" },
    { headword: "аузын ашса, жүрегі көрінеді", category: "idiom" },
    { headword: "тұсаукесер", category: "untranslatable" },
    { headword: "сұмдық", category: "slang" },
    { headword: "жаны мұрнының ұшында", category: "idiom" },
    { headword: "жеті ата", category: "untranslatable" },
    { headword: "қолы қолына жұқпайды", category: "idiom" },
    { headword: "ағайын", category: "untranslatable" },
    { headword: "аяғы жерге тимеді", category: "idiom" },
    { headword: "ит арқасы қиянда", category: "idiom" },
    { headword: "тілі ащы", category: "idiom" },
    { headword: "аузы-мұрны қисаймай", category: "idiom" },
    { headword: "қоян жүрек", category: "idiom" },
    { headword: "жүрегі тас төбесіне шықты", category: "idiom" },
    { headword: "тас бауыр", category: "idiom" },
    { headword: "қой аузынан шөп алмас", category: "idiom" },
    { headword: "жер-көкке сыйғызбады", category: "idiom" },
    { headword: "көзі жетті", category: "idiom" },
    { headword: "жаны қалмады", category: "idiom" },
    { headword: "ауыз бірлік", category: "idiom" },
    { headword: "қолы ұзын", category: "idiom" },
    { headword: "төбе шашы тік тұрды", category: "idiom" },
    { headword: "ит өлген жер", category: "idiom" },
    { headword: "екі езуі екі құлағында", category: "idiom" },
    { headword: "бір жағадан бас шығару", category: "idiom" },
    { headword: "ғой", category: "quirk" },
    { headword: "екен", category: "quirk" },
    { headword: "ше", category: "quirk" },
    { headword: "-ақ", category: "quirk" },
    { headword: "әрине", category: "quirk" },
    { headword: "жарайды", category: "quirk" },
    { headword: "әйтеуір", category: "quirk" },
  ],
};

/**
 * Hook words for a learning language. Returns an empty list for a language
 * that has no curated set yet — callers fall back to free-text input, so an
 * unknown code must never throw.
 */
export function getHookWords(lang: string): readonly HookWord[] {
  return HOOK_WORDS[lang] ?? [];
}

/** Every learning language that currently has a curated hook set. */
export function getHookWordLanguages(): readonly string[] {
  return Object.keys(HOOK_WORDS);
}
